# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
  apt update -y
  apt install -y linux-generic-hwe-20.04
  add-apt-repository ppa:deadsnakes/ppa
  apt update -y
  apt install -y python3.10
  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
  apt install -y python3.10-distutils
  apt install -y python3.10-venv
  apt install -y graphviz
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ipmininet"
  config.vm.box_url = "https://app.vagrantup.com/ipmininet/boxes/ubuntu-20.04/versions/1.1.0/providers/virtualbox.box"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "..", "/reverse-traceroute"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: $script, reboot: true
end
