.TH augsburg-traceroute-server 1
.SH NAME
augsburg-traceroute-server - reverse-traceroute server for augsburg-traceroute
.SH SYNOPSIS
.B augsburg-traceroute-server-[v4|v6]
[options]
.SH DESCRIPTION
.I  augsburg-traceroute-server
uses ICMP to create a reverse-traceroute endpoint.
It can be used as a target by the augsburg-traceroute-client.
.SH "SEE ALSO"
augsburg-traceroute-client(1)
