#!/bin/bash

set -e

PACKAGE_DIR=$(realpath "${PACKAGE_DIR:-$(pwd)/package}")

WORKDIR=$(mktemp -d)
HOOKDIR=$(realpath "$(dirname "$0")")/hooks
USER=$(id -u -n)

echo "$HOOKDIR"

cp -r "$(pwd)" "$WORKDIR/sources"

(
	cd "$WORKDIR/sources"

	VERSION=$(dpkg-parsechangelog --show-field Version | cut -d '-' -f 1)
	PACKAGE=$(dpkg-parsechangelog --show-field Source)

	debmake -yt
	cd "../$PACKAGE-$VERSION"

	sudo pbuilder update
	sudo pdebuild --buildresult "$PACKAGE_DIR" -- --use-network yes --hookdir "$HOOKDIR"
	sudo chown -R "$USER:$USER" "$PACKAGE_DIR"	
)

rm -f "$PACKAGE_DIR"/*_source.changes
rm -rf "$WORKDIR"

debsign --no-re-sign "$PACKAGE_DIR"/*.changes
