#include "config.h"

volatile const __u64 CONFIG_TIMEOUT_NS = DEFAULT_TIMEOUT_NS;
volatile const bool CONFIG_INDIRECT_TRACE_ENABLED =
    DEFAULT_INDIRECT_TRACE_ENABLED;
volatile const bool CONFIG_TCP_SYN_ENABLED = DEFAULT_TCP_SYN_ENABLED;